### ISSUE TITLE
Blood Magic: Sigil of the Green Grove

### ISSUE THREAD

**Issue by seear18** [IHOC/Server#1]
When i use Sigil of the Green Grove, its suppose to act as bonemeal on the ground, while it is working as bonemeal it is also breaking the block i am targeting and the bonemeal effect is still generated around that block. 

Also when you Activate Sigil of the Green Grove its suppose to drain your Life Storage and increase plant growth in a 9x9 (i think) around you. Instead it just breaks any crops i have planted randomly around me. 

I am Running Java Version 8 update 91
Windows 10
12 GB of Ram installed

**Comment by Gunner76th** [comment]
As this issue has now been resolved by the mod author in newer version of the mod, this issue is now being closed here as well. https://github.com/WayofTime/BloodMagic/issues/767
