### ISSUE TITLE
me slobberfrog and my friend dogdash24 got banned from the server it said the ban expires at 3/14/17 and it still wont let us join pls help we promise to be good

### ISSUE THREAD

**Issue by Slobberfrog** [IHOC/Server#13]
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods):

Narrative description of issue or crash:

Steps to reproduce the issue or crash:

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com):

Link to console logs (posted on http://gist.github.com):

OS of Client computer:

Version of JAVA on Client:

Version of Minecraft:

Version of Forge:

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):

**Comment by Gunner76th** [comment]
Sorry I was working on other bugs and issues and didnt notice it was past the time. You have both been pardoned. Further violations of the rules will result in either a 48hour ban or a perm ban depending on the crime.
