### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by seear18** [IHOC/Server#2]
http://pastebin.com/yXS7CN54

I am Running Java Version 8 update 91
Windows 10
12 GB of Ram installed

**Comment by Gunner76th** [comment]
@seear18 Please confirm your Java version. Open a command prompt, and type Java -version  to confirm your installed version. According to the above posted crash report, you are running Java 8 U 25.

**Comment by Gunner76th** [comment]
This report is now being marked as closed as the mod author has resolved the issue https://github.com/progwml6/ironchest/issues/69
