### ISSUE TITLE
Seear Crash 6/07

### ISSUE THREAD

**Issue by seear18** [IHOC/Server#3]
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods):
AllTheMods 1.10 v0.6

Steps to reproduce the issue or crash:
Tried to log in 3 more times, still wouldnt let me 

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com):
http://pastebin.com/tUcp3fzC

OS of Client computer:
Windows 10 

Version of JAVA on Client:
1.8.0_25

Version of Minecraft:
10.2

Version of Forge:
12.18.0.2007

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):
Allthemods, Spice of life and roguelikedungeons disabled

**Comment by seear18** [comment]
Update, Had a empty bucket on my bar i threw it off my bar with Q as i was logging in, because i wouldn't crash for a few seconds, also during the previous 3 i kept using my Air Sigil in my offhand to fly as far away from the chunk i could before the crash, chuck was 570,  -540 approx. had a Beehive, and some orange liquid on the ground. Buhbyenow was also there but didn't crash

**Comment by Gunner76th** [comment]
Issue has been fixed in release 1.6.4.7. Will update server once All The Mods pack has updated Gendustry. Until then, workaround is to not use an empty bucket on air.
