### ISSUE TITLE
Server login issue

### ISSUE THREAD

**Issue by ghost** [IHOC/Server#4]
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods): Sky Factory 3 Without Full screen window mod

Narrative description of issue or crash: Whenever I try to log onto a server this error comes up after giving me the prompt that i'm "logging in"

Steps to reproduce the issue or crash: Try to log onto the public multiplayer server

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com):

Link to console logs (posted on http://gist.github.com):
[fml-client-latest.txt](https://github.com/IHOC/Server/files/718377/fml-client-latest.txt)

OS of Client computer: Windows 10 64-bit

Version of JAVA on Client: 1.8.0_121 64-bit

Version of Minecraft: Latest installed but the modpack is using 1.10.2

Version of Forge: 1.2.0

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com): Sky Factory 3 Without Full screen window mod

**Comment by Gunner76th** [comment]
The issues seems to be because Fullscreened Window is a client and server mod pair. This was not something I was expecting, as there is nothing on the server that FW can do since the server does not have a GUI. in the config try editing the following line, changing yours to false:

> general {
>     # Enable Fullscreen Windowed (replaces Minecraft Fullscreen)
>     B:enableFullscreenWindowed=true

I am also going to submit an issue with the mod author about his mod for both the fact it is being required on servers when it should not be, and the fact that NVidia 950 cards specifically seem to be having issues with it. 

You will need to re-enable the FullscreenWindowed mod also.

**Comment by Gunner76th** [comment]
Please let me know if this fixes your issue. Also once we push out version 1.3 of the pack, I will be removing Fullscreened Window mod as IMO is has no useful purpose.

**Comment by Gunner76th** [comment]
@ASL1014 If you would please delete the version of Fullscreen Window mod that is on your client, and use the one that is linked in the referenced issue please. Let me know if your client continues to crash or if this fixes the issue.

**Comment by ghost** [comment]
When the new file is installed it still crashes and gives me the same error. It also say that there are outdated mods in the LLibrary

**Comment by Gunner76th** [comment]
CLosing ticket now that mod author has released a working version (even if it is a test build) that resolves this issue.
