### ISSUE TITLE
Diamond Saw Duplication with Refined Storage

### ISSUE THREAD

**Issue by miller4103** [IHOC/Server#6]
When submitting a bug report, to save us and yourself time, and to ensure we actually have the needed information to take care 
of your issue, please make sure you submit the following information (failure to provide all listed information may result in 
your bug not being addressed):

http://gist.github.com is the prefered site for all reports, logs, and lists.

TeamIHOC Server issue occurred on (Identified by modpack installed ie. All The Mods):

Narrative description of issue or crash:
**While you are in refined storage(Crafting Grid) you can duplicate Diamond Saws from 2 broken ones without the items being consumed.**

Steps to reproduce the issue or crash:
**Take two broken Diamond Saws and place the on the Top Right and Top Left of the crafting Grid in Refined Storage. Then the output window you can Make as many as you want without anything being consumed.**

Link to crash report (posted on either http://gist.github.com or http://www.pastebin.com):

Link to console logs (posted on http://gist.github.com):

OS of Client computer:
**Windows 10**

[Diamond Saw Duping.zip](https://github.com/IHOC/Server/files/737793/Diamond.Saw.Duping.zip)

Version of JAVA on Client:
**Version 8 Update 101 (Build 1.8.0_101-b13)**

Version of Minecraft:
**1.10.2**

Version of Forge:
**Unknown**

List of ALL mods installed (posted to either http://www.pastebin.com or http://gist.github.com):

**Comment by Gunner76th** [comment]
Please confirm that you did not have other saws in your storage system. It is possible that there were other saws in your storage system, of varying levels of damage, that were in fact being consumed to craft this. 

I will need to know which mod it is that adds the Diamond saw. I will check to see if this issue has been addressed by Refined Storage, and the mod for the diamond saw. If it has been already, the update that is coming soon (tm) should address this issue.

**Comment by miller4103** [comment]
The other saws with damage were not being consumed. I am not at home to check what mod it was from but I will do so once I get home. When I first found out about the glitch I started with a couple for crafting something. Then I had over 80 of them of different dam age quality.



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by miller4103** [comment]
The diamond saw was from chisel and bits.

________________________________

**Comment by Gunner76th** [comment]
Closed due to pack is now on a different version, and we are no longer using Refined Storage
