### ISSUE TITLE
SF3 Quantum Tanks Issue

### ISSUE THREAD

**Issue by SoulK1ller** [IHOC/Server#7]
Quantum tanks do not work in survival mod (single player or on the server). [Imgur pic of recipes required](http://imgur.com/a/qvMqI) The part that is broken is the "Get Your Tanks Here" mod. It requires you to create a wooden tank and then upgrade it to the required obsidian level. The quantum tank recipe does not see the upgraded tank as the correct tank. I have verified this multiple times. If you spawn in an obsidian tank using creative or the /give function, the quantum tank recipe works.

**Comment by Gunner76th** [comment]
Please confirm that you have crafted the tier 1 tank, then proceeded to apply the upgrades either by placing the tank in the world and slapping the upgrades to it, or by using the crafting grid. And that after having done this, you harvested the new upgraded take from the world, or pulled it from the crafting grid, and the new obsidian tank did not work as expected. 

If this can be confirmed as to not be working, i can look into submitting this report to the respective mod authors, as well as seeing if this has already been addressed on their end. Outside of that, the only thing I could do is look at creating a shaped crafting recipe for it using minetweaker/craftingtweaks that we have on the server.

**Comment by Gunner76th** [comment]
Issue has been fixed. Change recipe script to use Pressurized Fluid Tank form EnderIO.
