### ISSUE TITLE
Dark Soularium Jetplate not craftable

### ISSUE THREAD

**Issue by SoulK1ller** [IHOC/Server#8]
The tier 5 version of the jetpacks (Dark Soularium Jetplate) is not craftable. It requires an item called a Octadic Capacitor Pack (Armored) which does not exist in our current mod pack. I am asking if we can either add in the item, change the item required, or remove the Dark Soularium Jetplate from NEI.

**Comment by Gunner76th** [comment]
Recipe has been fixed.Wrong jetpack ID number was in the crafting script
