### ISSUE TITLE
Spawn issue

### ISSUE THREAD

**Issue by SoulK1ller** [IHOC/Server#9]
If you do /spawn it works just like intended. However, if you die and do not have a bed to respawn at, you start on top of spawn instead of in spawn. This is why there are 100+ graves below spawn. Confirmed this 3 times myself.

**Comment by Gunner76th** [comment]
This is a known bug/mechanic with forge. There is nothing that can be done other than to ensure that there is a 1x1 hole at the spawn coordinates.
